name: p2m
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - expat=2.7.3=h3385a95_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.25=h0dcde21_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.10.1
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiolimiter==1.2.1
      - aiosignal==1.4.0
      - alembic==1.16.5
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - autofaiss==1.10.0
      - beautifulsoup4==4.14.2
      - bert-score==0.3.13
      - cbor==1.0.0
      - cbor2==5.7.1
      - certifi==2025.10.5
      - charset-normalizer==3.4.4
      - click==8.1.8
      - colorama==0.4.6
      - colorlog==6.10.1
      - contourpy==1.3.0
      - cramjam==2.11.0
      - cycler==0.12.1
      - dataclasses==0.6
      - datasets==2.19.1
      - dill==0.3.7
      - distro==1.9.0
      - evaluate==0.4.6
      - exceptiongroup==1.3.0
      - faiss-cpu==1.12.0
      - fastapi==0.121.1
      - fastparquet==2024.11.0
      - fastuuid==0.14.0
      - ffmpy==0.6.4
      - filelock==3.19.1
      - fire==0.7.1
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2024.3.1
      - gradio==3.38.0
      - gradio-client==1.3.0
      - greenlet==3.2.4
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - ijson==3.4.0.post0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - indxr==0.1.5
      - iniconfig==2.1.0
      - inscriptis==2.6.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.7
      - krovetzstemmer==0.8
      - latex2mathml==3.78.1
      - linkify-it-py==2.0.3
      - litellm==1.79.3
      - llvmlite==0.43.0
      - lxml==6.0.2
      - lz4==4.4.5
      - mako==1.3.10
      - markdown==3.9
      - markdown-it-py==2.2.0
      - markupsafe==2.1.5
      - matplotlib==3.9.4
      - mdit-py-plugins==0.3.3
      - mdtex2html==1.3.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multipipe==0.1.0
      - multiprocess==0.70.15
      - narwhals==2.11.0
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nltk==3.9.2
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - oneliner-utils==0.1.2
      - openai==2.7.2
      - optuna==4.6.0
      - orjson==3.11.4
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.17.1
      - pillow==10.4.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - prompt2model==0.1.0
      - propcache==0.4.1
      - protobuf==6.33.0
      - psutil==7.1.3
      - pyarrow==12.0.1
      - pyarrow-hotfix==0.7
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyfiglet==1.0.4
      - pygments==2.19.2
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pystemmer==2.0.1
      - pytest==8.4.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.3
      - ranx==0.3.21
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.5
      - retriv==0.2.3
      - rich==14.2.0
      - rpds-py==0.27.1
      - sacrebleu==2.5.1
      - safetensors==0.6.2
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - sentence-transformers==5.1.2
      - sentencepiece==0.2.1
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.8
      - sqlalchemy==2.0.44
      - starlette==0.49.3
      - sympy==1.14.0
      - tabulate==0.9.0
      - termcolor==3.1.0
      - tevatron==0.1.0
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.57.1
      - trec-car-tools==2.6
      - triton==3.4.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - umap-learn==0.5.9.post2
      - unidecode==1.4.0
      - unlzw3==0.2.3
      - urllib3==2.5.0
      - uv==0.9.9
      - uvicorn==0.38.0
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - websockets==11.0.3
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zlib-state==0.1.10
      - ir-datasets
prefix: /home/chenyusiyuan/miniconda3/envs/p2m
